global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'teddy-monitor'

scrape_configs:
  - job_name: 'teddy-backend'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['teddy_postgres:5432']
